/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as TadRouteImport } from './routes/tad'
import { Route as SuggestionRouteImport } from './routes/suggestion'
import { Route as StopsRouteImport } from './routes/stops'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as GtfsRtRouteImport } from './routes/gtfs-rt'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActiosaeRouteImport } from './routes/actiosae'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StopsStopIdRouteImport } from './routes/stops.$stopId'
import { Route as ArrivalsStopIdRouteImport } from './routes/arrivals.$stopId'
import { Route as ApiPublicInitAdminRouteImport } from './routes/api.public.init-admin'
import { Route as ApiPublicAdsRouteImport } from './routes/api.public.ads'
import { Route as ApiPublicGtfsStaticFileRouteImport } from './routes/api.public.gtfs-static.$file'
import { Route as ApiPublicActiosaeGtfsFileRouteImport } from './routes/api.public.actiosae.gtfs.$file'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const TadRoute = TadRouteImport.update({
  id: '/tad',
  path: '/tad',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestionRoute = SuggestionRouteImport.update({
  id: '/suggestion',
  path: '/suggestion',
  getParentRoute: () => rootRouteImport,
} as any)
const StopsRoute = StopsRouteImport.update({
  id: '/stops',
  path: '/stops',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const GtfsRtRoute = GtfsRtRouteImport.update({
  id: '/gtfs-rt',
  path: '/gtfs-rt',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiosaeRoute = ActiosaeRouteImport.update({
  id: '/actiosae',
  path: '/actiosae',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StopsStopIdRoute = StopsStopIdRouteImport.update({
  id: '/$stopId',
  path: '/$stopId',
  getParentRoute: () => StopsRoute,
} as any)
const ArrivalsStopIdRoute = ArrivalsStopIdRouteImport.update({
  id: '/arrivals/$stopId',
  path: '/arrivals/$stopId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInitAdminRoute = ApiPublicInitAdminRouteImport.update({
  id: '/api/public/init-admin',
  path: '/api/public/init-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdsRoute = ApiPublicAdsRouteImport.update({
  id: '/api/public/ads',
  path: '/api/public/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGtfsStaticFileRoute = ApiPublicGtfsStaticFileRouteImport.update({
  id: '/api/public/gtfs-static/$file',
  path: '/api/public/gtfs-static/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicActiosaeGtfsFileRoute =
  ApiPublicActiosaeGtfsFileRouteImport.update({
    id: '/api/public/actiosae/gtfs/$file',
    path: '/api/public/actiosae/gtfs/$file',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actiosae': typeof ActiosaeRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/explorer': typeof ExplorerRoute
  '/gtfs-rt': typeof GtfsRtRoute
  '/routes': typeof RoutesRoute
  '/stops': typeof StopsRouteWithChildren
  '/suggestion': typeof SuggestionRoute
  '/tad': typeof TadRoute
  '/vehicles': typeof VehiclesRoute
  '/arrivals/$stopId': typeof ArrivalsStopIdRoute
  '/stops/$stopId': typeof StopsStopIdRoute
  '/api/public/ads': typeof ApiPublicAdsRoute
  '/api/public/init-admin': typeof ApiPublicInitAdminRoute
  '/api/public/gtfs-static/$file': typeof ApiPublicGtfsStaticFileRoute
  '/api/public/actiosae/gtfs/$file': typeof ApiPublicActiosaeGtfsFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actiosae': typeof ActiosaeRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/explorer': typeof ExplorerRoute
  '/gtfs-rt': typeof GtfsRtRoute
  '/routes': typeof RoutesRoute
  '/stops': typeof StopsRouteWithChildren
  '/suggestion': typeof SuggestionRoute
  '/tad': typeof TadRoute
  '/vehicles': typeof VehiclesRoute
  '/arrivals/$stopId': typeof ArrivalsStopIdRoute
  '/stops/$stopId': typeof StopsStopIdRoute
  '/api/public/ads': typeof ApiPublicAdsRoute
  '/api/public/init-admin': typeof ApiPublicInitAdminRoute
  '/api/public/gtfs-static/$file': typeof ApiPublicGtfsStaticFileRoute
  '/api/public/actiosae/gtfs/$file': typeof ApiPublicActiosaeGtfsFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actiosae': typeof ActiosaeRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/explorer': typeof ExplorerRoute
  '/gtfs-rt': typeof GtfsRtRoute
  '/routes': typeof RoutesRoute
  '/stops': typeof StopsRouteWithChildren
  '/suggestion': typeof SuggestionRoute
  '/tad': typeof TadRoute
  '/vehicles': typeof VehiclesRoute
  '/arrivals/$stopId': typeof ArrivalsStopIdRoute
  '/stops/$stopId': typeof StopsStopIdRoute
  '/api/public/ads': typeof ApiPublicAdsRoute
  '/api/public/init-admin': typeof ApiPublicInitAdminRoute
  '/api/public/gtfs-static/$file': typeof ApiPublicGtfsStaticFileRoute
  '/api/public/actiosae/gtfs/$file': typeof ApiPublicActiosaeGtfsFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actiosae'
    | '/admin'
    | '/alerts'
    | '/explorer'
    | '/gtfs-rt'
    | '/routes'
    | '/stops'
    | '/suggestion'
    | '/tad'
    | '/vehicles'
    | '/arrivals/$stopId'
    | '/stops/$stopId'
    | '/api/public/ads'
    | '/api/public/init-admin'
    | '/api/public/gtfs-static/$file'
    | '/api/public/actiosae/gtfs/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actiosae'
    | '/admin'
    | '/alerts'
    | '/explorer'
    | '/gtfs-rt'
    | '/routes'
    | '/stops'
    | '/suggestion'
    | '/tad'
    | '/vehicles'
    | '/arrivals/$stopId'
    | '/stops/$stopId'
    | '/api/public/ads'
    | '/api/public/init-admin'
    | '/api/public/gtfs-static/$file'
    | '/api/public/actiosae/gtfs/$file'
  id:
    | '__root__'
    | '/'
    | '/actiosae'
    | '/admin'
    | '/alerts'
    | '/explorer'
    | '/gtfs-rt'
    | '/routes'
    | '/stops'
    | '/suggestion'
    | '/tad'
    | '/vehicles'
    | '/arrivals/$stopId'
    | '/stops/$stopId'
    | '/api/public/ads'
    | '/api/public/init-admin'
    | '/api/public/gtfs-static/$file'
    | '/api/public/actiosae/gtfs/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActiosaeRoute: typeof ActiosaeRoute
  AdminRoute: typeof AdminRoute
  AlertsRoute: typeof AlertsRoute
  ExplorerRoute: typeof ExplorerRoute
  GtfsRtRoute: typeof GtfsRtRoute
  RoutesRoute: typeof RoutesRoute
  StopsRoute: typeof StopsRouteWithChildren
  SuggestionRoute: typeof SuggestionRoute
  TadRoute: typeof TadRoute
  VehiclesRoute: typeof VehiclesRoute
  ArrivalsStopIdRoute: typeof ArrivalsStopIdRoute
  ApiPublicAdsRoute: typeof ApiPublicAdsRoute
  ApiPublicInitAdminRoute: typeof ApiPublicInitAdminRoute
  ApiPublicGtfsStaticFileRoute: typeof ApiPublicGtfsStaticFileRoute
  ApiPublicActiosaeGtfsFileRoute: typeof ApiPublicActiosaeGtfsFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tad': {
      id: '/tad'
      path: '/tad'
      fullPath: '/tad'
      preLoaderRoute: typeof TadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggestion': {
      id: '/suggestion'
      path: '/suggestion'
      fullPath: '/suggestion'
      preLoaderRoute: typeof SuggestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stops': {
      id: '/stops'
      path: '/stops'
      fullPath: '/stops'
      preLoaderRoute: typeof StopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gtfs-rt': {
      id: '/gtfs-rt'
      path: '/gtfs-rt'
      fullPath: '/gtfs-rt'
      preLoaderRoute: typeof GtfsRtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actiosae': {
      id: '/actiosae'
      path: '/actiosae'
      fullPath: '/actiosae'
      preLoaderRoute: typeof ActiosaeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stops/$stopId': {
      id: '/stops/$stopId'
      path: '/$stopId'
      fullPath: '/stops/$stopId'
      preLoaderRoute: typeof StopsStopIdRouteImport
      parentRoute: typeof StopsRoute
    }
    '/arrivals/$stopId': {
      id: '/arrivals/$stopId'
      path: '/arrivals/$stopId'
      fullPath: '/arrivals/$stopId'
      preLoaderRoute: typeof ArrivalsStopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/init-admin': {
      id: '/api/public/init-admin'
      path: '/api/public/init-admin'
      fullPath: '/api/public/init-admin'
      preLoaderRoute: typeof ApiPublicInitAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ads': {
      id: '/api/public/ads'
      path: '/api/public/ads'
      fullPath: '/api/public/ads'
      preLoaderRoute: typeof ApiPublicAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gtfs-static/$file': {
      id: '/api/public/gtfs-static/$file'
      path: '/api/public/gtfs-static/$file'
      fullPath: '/api/public/gtfs-static/$file'
      preLoaderRoute: typeof ApiPublicGtfsStaticFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/actiosae/gtfs/$file': {
      id: '/api/public/actiosae/gtfs/$file'
      path: '/api/public/actiosae/gtfs/$file'
      fullPath: '/api/public/actiosae/gtfs/$file'
      preLoaderRoute: typeof ApiPublicActiosaeGtfsFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StopsRouteChildren {
  StopsStopIdRoute: typeof StopsStopIdRoute
}

const StopsRouteChildren: StopsRouteChildren = {
  StopsStopIdRoute: StopsStopIdRoute,
}

const StopsRouteWithChildren = StopsRoute._addFileChildren(StopsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActiosaeRoute: ActiosaeRoute,
  AdminRoute: AdminRoute,
  AlertsRoute: AlertsRoute,
  ExplorerRoute: ExplorerRoute,
  GtfsRtRoute: GtfsRtRoute,
  RoutesRoute: RoutesRoute,
  StopsRoute: StopsRouteWithChildren,
  SuggestionRoute: SuggestionRoute,
  TadRoute: TadRoute,
  VehiclesRoute: VehiclesRoute,
  ArrivalsStopIdRoute: ArrivalsStopIdRoute,
  ApiPublicAdsRoute: ApiPublicAdsRoute,
  ApiPublicInitAdminRoute: ApiPublicInitAdminRoute,
  ApiPublicGtfsStaticFileRoute: ApiPublicGtfsStaticFileRoute,
  ApiPublicActiosaeGtfsFileRoute: ApiPublicActiosaeGtfsFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
