/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as TadRouteImport } from './routes/tad'
import { Route as SuggestionRouteImport } from './routes/suggestion'
import { Route as StopsRouteImport } from './routes/stops'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as GtfsRtRouteImport } from './routes/gtfs-rt'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StopsStopIdRouteImport } from './routes/stops.$stopId'
import { Route as ArrivalsStopIdRouteImport } from './routes/arrivals.$stopId'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const TadRoute = TadRouteImport.update({
  id: '/tad',
  path: '/tad',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestionRoute = SuggestionRouteImport.update({
  id: '/suggestion',
  path: '/suggestion',
  getParentRoute: () => rootRouteImport,
} as any)
const StopsRoute = StopsRouteImport.update({
  id: '/stops',
  path: '/stops',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const GtfsRtRoute = GtfsRtRouteImport.update({
  id: '/gtfs-rt',
  path: '/gtfs-rt',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StopsStopIdRoute = StopsStopIdRouteImport.update({
  id: '/$stopId',
  path: '/$stopId',
  getParentRoute: () => StopsRoute,
} as any)
const ArrivalsStopIdRoute = ArrivalsStopIdRouteImport.update({
  id: '/arrivals/$stopId',
  path: '/arrivals/$stopId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/gtfs-rt': typeof GtfsRtRoute
  '/routes': typeof RoutesRoute
  '/stops': typeof StopsRouteWithChildren
  '/suggestion': typeof SuggestionRoute
  '/tad': typeof TadRoute
  '/vehicles': typeof VehiclesRoute
  '/arrivals/$stopId': typeof ArrivalsStopIdRoute
  '/stops/$stopId': typeof StopsStopIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/gtfs-rt': typeof GtfsRtRoute
  '/routes': typeof RoutesRoute
  '/stops': typeof StopsRouteWithChildren
  '/suggestion': typeof SuggestionRoute
  '/tad': typeof TadRoute
  '/vehicles': typeof VehiclesRoute
  '/arrivals/$stopId': typeof ArrivalsStopIdRoute
  '/stops/$stopId': typeof StopsStopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/gtfs-rt': typeof GtfsRtRoute
  '/routes': typeof RoutesRoute
  '/stops': typeof StopsRouteWithChildren
  '/suggestion': typeof SuggestionRoute
  '/tad': typeof TadRoute
  '/vehicles': typeof VehiclesRoute
  '/arrivals/$stopId': typeof ArrivalsStopIdRoute
  '/stops/$stopId': typeof StopsStopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/gtfs-rt'
    | '/routes'
    | '/stops'
    | '/suggestion'
    | '/tad'
    | '/vehicles'
    | '/arrivals/$stopId'
    | '/stops/$stopId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/gtfs-rt'
    | '/routes'
    | '/stops'
    | '/suggestion'
    | '/tad'
    | '/vehicles'
    | '/arrivals/$stopId'
    | '/stops/$stopId'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/gtfs-rt'
    | '/routes'
    | '/stops'
    | '/suggestion'
    | '/tad'
    | '/vehicles'
    | '/arrivals/$stopId'
    | '/stops/$stopId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  GtfsRtRoute: typeof GtfsRtRoute
  RoutesRoute: typeof RoutesRoute
  StopsRoute: typeof StopsRouteWithChildren
  SuggestionRoute: typeof SuggestionRoute
  TadRoute: typeof TadRoute
  VehiclesRoute: typeof VehiclesRoute
  ArrivalsStopIdRoute: typeof ArrivalsStopIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tad': {
      id: '/tad'
      path: '/tad'
      fullPath: '/tad'
      preLoaderRoute: typeof TadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggestion': {
      id: '/suggestion'
      path: '/suggestion'
      fullPath: '/suggestion'
      preLoaderRoute: typeof SuggestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stops': {
      id: '/stops'
      path: '/stops'
      fullPath: '/stops'
      preLoaderRoute: typeof StopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gtfs-rt': {
      id: '/gtfs-rt'
      path: '/gtfs-rt'
      fullPath: '/gtfs-rt'
      preLoaderRoute: typeof GtfsRtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stops/$stopId': {
      id: '/stops/$stopId'
      path: '/$stopId'
      fullPath: '/stops/$stopId'
      preLoaderRoute: typeof StopsStopIdRouteImport
      parentRoute: typeof StopsRoute
    }
    '/arrivals/$stopId': {
      id: '/arrivals/$stopId'
      path: '/arrivals/$stopId'
      fullPath: '/arrivals/$stopId'
      preLoaderRoute: typeof ArrivalsStopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StopsRouteChildren {
  StopsStopIdRoute: typeof StopsStopIdRoute
}

const StopsRouteChildren: StopsRouteChildren = {
  StopsStopIdRoute: StopsStopIdRoute,
}

const StopsRouteWithChildren = StopsRoute._addFileChildren(StopsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  GtfsRtRoute: GtfsRtRoute,
  RoutesRoute: RoutesRoute,
  StopsRoute: StopsRouteWithChildren,
  SuggestionRoute: SuggestionRoute,
  TadRoute: TadRoute,
  VehiclesRoute: VehiclesRoute,
  ArrivalsStopIdRoute: ArrivalsStopIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
